// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vongglbllhyyyrjbgzfo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZvbmdnbGJsbGh5eXlyamJnemZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA0OTk3OTcsImV4cCI6MjA2NjA3NTc5N30.Va_TeIW8WF7Pi8gMhMxh8heCMMk0FMSLooQ0LWsiPLY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);